version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archive_dag
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  # No need for redis for now
  #redis:
  #  image: redis
  #  ports:
  #    - "6379:6379"
  #  restart: always
  #  volumes:
  #    - ./data/redis:/data
  etcd:
    image: bitnami/etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./data/etcd:/bitnami/etcd
