server:
  port: 8888
  max-http-header-size: 16MB
grpc:
  server:
    port: 9090
    reflection-service-enabled: true
    security:
      enabled: true
      certificate-chain: file:ssl/localhost.crt
      private-key: file:ssl/localhost.key
      trust-cert-collection: file:ssl/rootCA.crt
      client-auth: require
cert-signing:
  ca-cert: file:ssl/rootCA.crt
  ca-private-key: file:ssl/rootCA.key
  custom-subject-d-n: O=SkyBlond
spring:
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/archive_dag
    password: password
    username: postgres
  redis:
    database: 0
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 256GB
      max-request-size: 257GB
archive-dag.ariteg:
  storage:
    type: file_system
    primary-hash-type: sha3_512
    secondary-hash-type: blake2b_512
    filesystem:
      path: "./data/protos"
      threadSize: 16
      queue-size: 1024
  meta:
    lock-expire-duration: 15
    lock-expire-time-unit: minutes
jwt:
  secret: r5FHVELtfN5CdTLGJ6ZwEEBCNFn4nTr5ig6SwpXbj2nQuWYsOn/EJyqEWvEm4J0NOYdmC51+kdX2efPZRhTYzA==
  expire-in-duration: 30
  expire-in-unit: minutes
