server:
  port: 8888
  max-http-header-size: 16MB
grpc:
  server:
    port: 9090
    reflection-service-enabled: true
    security:
      enabled: true
      certificate-chain: file:ssl/localhost.crt
      private-key: file:ssl/localhost.key
      client-auth: require
cert-signing:
  subject-dn-c: China
  subject-dn-o: SkyBlond
  subject-dn-o-u: R&D
spring:
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.172.3.101:5432/archive_dag
    password: password
    username: postgres
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 256GB
      max-request-size: 257GB
ariteg:
  storage:
    #    type: LOCAL_WITH_S3_BACKUP # local_file_system_only
    type: local_file_system_only
    threadSize: 16
    queue-size: 2048
    filesystem:
      path: "D:\\test\\archive-dag"
    s3:
      endpoint: http://10.172.3.100:9000
      accessKey: archive-dag
      secretKey: archive-dag
      region: global
      bucket-name: archive-dag-test
      upload-storage-class: standard
etcd:
  server-addr:
    - "http://10.172.3.101:2379"
